author: David Souza Pinto
title: David Souza
description: Industrial Engineer, Lean Six Sigma Black Belt, Data Scientist
keywords: "Industrial Engineering, Operations Management, 
          Supply Chain Management, Production Planning, 
          Inventory Management, Lean Six Sigma, 
          Continuous Improvement, Machine Learning, Data Analysis, 
          Data Visualisation, Numerical Analysis,
          Operations Research, Simulation, Programming, 
          R, Python, D3, JavaScript, Julia, Ruby, Swift, LaTeX"

baseurl: ""
url: https://souzapd.github.io/

highlighter: rouge
markdown: kramdown
permalink: /p/:title/

linkedin: souzapd
github: souzapd
orcid: 0000-0002-3076-4007
flickr: souzapd
