author: David Souza Pinto
pagetitle: David Souza

keywords: > 
  analytics engineering, advanced analytics, data analysis, 
  decision support, simulation, design of experiments,
  data visualisation

tagline: >
  Advanced Analytics · Data Visualisation

aboutme: |
  Analytics specialist with six years of experience transforming data into solutions
  that drive decision-making and operations. I am also experienced with continuous
  improvement (kaizen), having spearheaded initiatives to improve business processes
  using Six Sigma and to promote data literacy. I have supported local and
  international teams across various industries, such as Energy, Education, and
  Consumer Packaged Goods (CPG).


baseurl: ""
url: https://souzapd.github.io/

highlighter: rouge
markdown: kramdown

linkedin: souzapd
github: souzapd
