author: David Souza Pinto
pagetitle: David Souza

keywords: > 
  analytics engineering, advanced analytics, data analysis, 
  decision support, simulation, design of experiments,
  data visualisation

tagline: >
  Advanced Analytics · Data Visualisation

aboutme: >
  Analytics specialist with six years of experience transforming data into solutions that drive decision-making and operations.


baseurl: ""
url: https://souzapd.github.io/

highlighter: rouge
markdown: kramdown

linkedin: souzapd
github: souzapd
