author: David Souza Pinto
pagetitle: David Souza

keywords: > 
  analytics engineering, statistical learning, 
  statistical machine learning, machine learning, 
  time series forecasting, data analysis, 
  simulation, r, python, quarto, sql, data engineering, 
  decision support, operations research, lean six sigma, kaizen, 
  operations management, supply chain operations,
  scheduling, production planning, inventory management

tagline: >
  Analytics Engineering · Machine Learning · Data Visualisation

aboutme: >
  I am an Analytics Specialist with a MSc in Industrial Engineering
  and six years of experience transforming data into tools that
  support decision-making across varied industries.



baseurl: ""
url: https://souzapd.github.io/

highlighter: rouge
markdown: kramdown

linkedin: souzapd
github: souzapd
