author: David Souza Pinto
pagetitle: David Souza

keywords: > 
  analytics engineering, advanced analytics, data analysis, 
  decision support, simulation, design of experiments,
  data visualisation

tagline: >
  Advanced Analytics · Six Sigma

aboutme: |
  Analytics specialist with five years of experience transforming data
  into solutions that drive decision-making. By drawing on my expertise in
  Six Sigma, analytics engineering, and applied statistics,
  I have supported local and global teams in Energy, Education,
  and Consumer Packaged Goods (CPG) in executing projects of varied
  scale and scope.

baseurl: ""
url: https://souzapd.github.io/

highlighter: rouge
markdown: kramdown

linkedin: souzapd
github: souzapd
