author: David Souza Pinto
pagetitle: David Souza

keywords: > 
  analytics engineering, advanced analytics, data analysis, 
  decision support, simulation, design of experiments,
  data visualisation

tagline: >
  Analytics Engineering · Data Visualisation

aboutme: >
  Analytics Specialist with six years of experience in data-driven decision-making.
  I combine analytics engineering and machine learning
  to transform data into products that support daily operations.


baseurl: ""
url: https://souzapd.github.io/

highlighter: rouge
markdown: kramdown

linkedin: souzapd
github: souzapd
