author: David Souza Pinto
pagetitle: David Souza

keywords: > 
  analytics engineering, advanced analytics, data analysis, 
  decision support, simulation, design of experiments,
  data visualisation

tagline: >
  Analytics Engineering · Data Visualisation

aboutme: >
  I am an Analytics Specialist with a MSc in Industrial Engineering
  and six years of experience transforming data into tools that
  support decision-making.



baseurl: ""
url: https://souzapd.github.io/

highlighter: rouge
markdown: kramdown

linkedin: souzapd
github: souzapd
