author: David Souza Pinto
pagetitle: David Souza

keywords: > 
  "Operations Management, Scheduling, Production Planning, 
  Inventory Management, Operations Research, Decision Support, Lean Six Sigma, 
  Data Analysis, Simulation, Programming, R, Python, LaTeX"

aboutme: >
  Analytics Specialist with a MSc in Industrial Engineering and 6 years of 
  experience using advanced analytics to support decision-making. I excel at 
  analytics engineering, statistical machine learning, and data visualisation.

  These skills allow me to transform business data into solutions that support
  daily operations. I have delivered reduced data usage by optimising queries
  against data warehouses; automated reports for OKR tracking; and implemented
  time series forecasting models for operations planning.

  I am also a strong proponent of kaizen (continuous improvement), having
  spearheaded initiatives to improve business processes using Six Sigma and
  to promote data literacy. I have experience supporting local and
  international teams in delivering analytics solutions across various
  industries, such as Energy, Education, and Food.

  Tools and technologies I use:

  * Languages: SQL, R, Python.
  * Reporting: Quarto, Excel, PowerPoint.
  * Databases: PostgreSQL, MariaDB.
  * Cloud data warehouses: Google BigQuery, Amazon Redshift, Snowflake.


baseurl: ""
url: https://souzapd.github.io/

highlighter: rouge
markdown: kramdown

linkedin: souzapd
github: souzapd
